print("Hello World")
print('こんにちは',end='')
print('はじめまして')
print('風\n林\n火\n林\n')
name=input('何か入力してください:') 
print('あいうえお')
print('a','bc')
print('d','e')
print('1|2|3','4','5')
print('あいうえお')
print('かきくけこ')
print(int('12'),end='')
print('あいうえお')